// generated by mBlock5 for mBot
// codes make you happy

#include <MeMCore.h>
#include <Arduino.h>
#include <Wire.h>
#include <SoftwareSerial.h>

double currentTime = 0;
double lastTime = 0;
MeLineFollower linefollower_2(2);
MeDCMotor motor_9(9);
MeDCMotor motor_10(10);
MeRGBLed rgbled_7(7, 2);
MeBuzzer buzzer;

float soundDuration = 0;
float silenceDuration = 0;
float currentPitch = 0;
float numberOfBeeps = 0;
float numberOfBlinks = 0;
float targetRedIntensity = 0;
float targetGreenIntensity = 0;
float targetBlueIntensity = 0;
float currentRedIntensity = 0;
float currentGreenIntensity = 0;
float currentBlueIntensity = 0;
float color = 0;
float onDuration = 0;
float offDuration = 0;
float currentSpeed = 0;
float leftWheelPower = 0;
float rightWheelPower = 0;
float turnCycle = 0;
float blinkCycle = 0;
float beepCycle = 0;
float blinkFrequency = 0;
float turnDuration = 0;
float forwardDuration = 0;
float turnSpeed = 0;
float isTurning = 0;
float x = 0;
float doWander = 0;
float doBeep = 0;
float doBlink = 0;
float n = 0;
float timesButtonPressed = 0;

double getLastTime(){
  return currentTime = millis() / 1000.0 - lastTime;
}
void move(int direction, int speed) {
  int leftSpeed = 0;
  int rightSpeed = 0;
  if(direction == 1) {
    leftSpeed = speed;
    rightSpeed = speed;
  } else if(direction == 2) {
    leftSpeed = -speed;
    rightSpeed = -speed;
  } else if(direction == 3) {
    leftSpeed = -speed;
    rightSpeed = speed;
  } else if(direction == 4) {
    leftSpeed = speed;
    rightSpeed = -speed;
  }
  motor_9.run((9) == M1 ? -(leftSpeed) : (leftSpeed));
  motor_10.run((10) == M1 ? -(rightSpeed) : (rightSpeed));
}
void WanderBlinkBeep_N_wander_N_S_N_N_N_B_blink_N_N_S_N_beep_N_N_S_N(double duration, double wanderSpeed, String wanderAcceleration, double wanderRoundness, double wanderTurnRate, double wanderPhase, boolean stayInBounds, double blinkTemperature, double blinkTempo, String blinkMode, double blinkPhase, double beepPitch, double beepTempo, String beepIntonation, double beepPhase){
  CheckValidWanderInput_N_S_N_N_N(wanderSpeed, wanderAcceleration, wanderRoundness, wanderTurnRate, wanderPhase);
  if(doWander == 1.000000){
    turnDuration = ((0.2 * wanderRoundness + 0.6)) / wanderTurnRate;
    if(turnDuration > (1.4 * wanderRoundness + 0.6)){
      turnDuration = (1.4 * wanderRoundness + 0.6);

    }
    forwardDuration = ((1 / wanderTurnRate - turnDuration));
    turnSpeed = ((wanderSpeed * wanderRoundness - wanderSpeed / 2));
    turnCycle = 0;

  }
  CheckValidBlinkInput_N_N_S_N(blinkTemperature, blinkTempo, blinkMode, blinkPhase);
  if(doBlink == 1.000000){
    blinkCycle = 0;
    x = 1;
    if(blinkTemperature == 0.500000){
      targetRedIntensity = 200;
      targetGreenIntensity = 255;
      targetBlueIntensity = 0;

    }
    if(blinkTemperature > 0.5){
      targetRedIntensity = round(((110 * blinkTemperature + 145)));
      targetGreenIntensity = round(((-510 * blinkTemperature + 510)));
      targetBlueIntensity = 0;

    }
    if(blinkTemperature < 0.5){
      targetRedIntensity = round((100 * blinkTemperature));
      targetGreenIntensity = round((510 * blinkTemperature));
      targetBlueIntensity = round(((-510 * blinkTemperature + 255)));

    }
    if(blinkMode == "Constant"){
      onDuration = 1 / (2 * blinkTempo);

    }else{
      onDuration = 1 / blinkTempo;

    }

  }
  CheckValidBeepInput_N_N_S_N(beepPitch, beepTempo, beepIntonation, beepPhase);
  if(doBeep == 1.000000){
    beepCycle = 0;
    n = 0;
    currentPitch = beepPitch;
    if(beepIntonation == "Constant"){
      soundDuration = 0.8 * (1 / beepTempo);

    }
    if((beepIntonation == "Rising")  ||  (beepIntonation == "Falling")){
      soundDuration = (0.8 * (1 / beepTempo)) / 12;

    }else{
      soundDuration = (0.8 * (1 / beepTempo)) / 24;

    }
    silenceDuration = ((1 / beepTempo - soundDuration));

  }
  lastTime = millis() / 1000.0;
  while(!(getLastTime() > duration))
  {
    _loop();
    if(doWander == 1.000000){
      if(((getLastTime() - wanderPhase) > 0)  ||  ((getLastTime() - wanderPhase) == 0.000000)){
        if(stayInBounds){
          if((0 ? (1 == 0 ? linefollower_2.readSensors() == 0 :
          (linefollower_2.readSensors() & 1) == 1) :
          (1 == 0 ? linefollower_2.readSensors() == 3 :
          (linefollower_2.readSensors() & 1) == 0))){

            move(3, 100 / 100.0 * 255);
            _delay(0.5);
            move(3, 0);

          }
          if((0 ? (2 == 0 ? linefollower_2.readSensors() == 0 :
          (linefollower_2.readSensors() & 2) == 2) :
          (2 == 0 ? linefollower_2.readSensors() == 3 :
          (linefollower_2.readSensors() & 2) == 0))){

            move(4, 100 / 100.0 * 255);
            _delay(0.5);
            move(4, 0);

          }

        }
        if((getLastTime() - wanderPhase) < (turnCycle / wanderTurnRate + forwardDuration)){

          move(1, wanderSpeed / 100.0 * 255);

        }else{
          if(fmod(turnCycle, 2) == 0.000000){

            motor_9.run(-1 * wanderSpeed/100.0*255);
            motor_10.run(turnSpeed/100.0*255);

          }else{

            motor_9.run(-1 * turnSpeed/100.0*255);
            motor_10.run(wanderSpeed/100.0*255);

          }

        }
        if((getLastTime() - wanderPhase) > ((turnCycle + 1)) / wanderTurnRate){
          turnCycle += 1;

        }

      }

    }
    if(doBlink == 1.000000){
      if(((getLastTime() - blinkPhase) > 0)  ||  ((getLastTime() - blinkPhase) == 0.000000)){
        if(blinkMode == "Constant"){
          if((getLastTime() - blinkPhase) < (blinkCycle / blinkTempo + onDuration)){

            rgbled_7.setColor(0, targetRedIntensity, targetGreenIntensity, targetBlueIntensity);
            rgbled_7.show();

          }else{

            rgbled_7.setColor(0, 0, 0, 0);
            rgbled_7.show();

          }

        }
        if(blinkMode == "Rising"){
          if((getLastTime() - blinkPhase) < (blinkCycle / blinkTempo + (x * onDuration) / 100)){

            rgbled_7.setColor(0, round(((x * targetRedIntensity) / 100)), round(((x * targetGreenIntensity) / 100)), round(((x * targetBlueIntensity) / 100)));
            rgbled_7.show();

          }else{
            x += 1;

          }

        }
        if(blinkMode == "Falling"){
          if((getLastTime() - blinkPhase) < (blinkCycle / blinkTempo + (x * onDuration) / 100)){

            rgbled_7.setColor(0, round(((((100 - x)) * targetRedIntensity) / 100)), round(((((100 - x)) * targetGreenIntensity) / 100)), round(((((100 - x)) * targetBlueIntensity) / 100)));
            rgbled_7.show();

          }else{
            x += 1;

          }

        }
        if(blinkMode == "Rising-Falling"){
          if((getLastTime() - blinkPhase) < (blinkCycle / blinkTempo + (x * onDuration) / 200)){
            if(x < 100){

              rgbled_7.setColor(0, round(((x * targetRedIntensity) / 100)), round(((x * targetGreenIntensity) / 100)), round(((x * targetBlueIntensity) / 100)));
              rgbled_7.show();

            }else{

              rgbled_7.setColor(0, round(((((200 - x)) * targetRedIntensity) / 100)), round(((((200 - x)) * targetGreenIntensity) / 100)), round(((((200 - x)) * targetBlueIntensity) / 100)));
              rgbled_7.show();

            }

          }else{
            x += 1;

          }

        }
        if(blinkMode == "Falling-Rising"){
          if((getLastTime() - blinkPhase) < (blinkCycle / blinkTempo + (x * onDuration) / 200)){
            if(x < 100){

              rgbled_7.setColor(0, round(((((100 - x)) * targetRedIntensity) / 100)), round(((((100 - x)) * targetGreenIntensity) / 100)), round(((((100 - x)) * targetBlueIntensity) / 100)));
              rgbled_7.show();

            }else{

              rgbled_7.setColor(0, round(((((x - 100)) * targetRedIntensity) / 100)), round(((((x - 100)) * targetGreenIntensity) / 100)), round(((((x - 100)) * targetBlueIntensity) / 100)));
              rgbled_7.show();

            }

          }else{
            x += 1;

          }

        }
        if((getLastTime() - blinkPhase) > ((blinkCycle + 1)) / blinkTempo){
          blinkCycle += 1;
          x = 1;

        }

      }

    }
    if(doBeep == 1.000000){
      if(((getLastTime() - beepPhase) > 0)  ||  ((getLastTime() - beepPhase) == 0.000000)){
        if(beepIntonation == "Constant"){
          if((getLastTime() - beepPhase) < (beepCycle / beepTempo + ((n + 1)) * soundDuration)){

            buzzer.tone(currentPitch, soundDuration * 1000);
            _delay(float(silenceDuration));

          }

        }
        if(beepIntonation == "Rising"){
          if((getLastTime() - beepPhase) < (beepCycle / beepTempo + ((n + 1)) * soundDuration)){

            buzzer.tone(currentPitch, soundDuration * 1000);
            _delay(float(silenceDuration));

          }else{
            n += 1;
            currentPitch = exp((log(beepPitch) + (n / 12) * log(2)));

          }

        }
        if(beepIntonation == "Falling"){
          if((getLastTime() - beepPhase) < (beepCycle / beepTempo + ((n + 1)) * soundDuration)){

            buzzer.tone(currentPitch, soundDuration * 1000);
            _delay(float(silenceDuration));

          }else{
            n += 1;
            currentPitch = exp((log(beepPitch) - (n / 12) * log(2)));

          }

        }
        if(beepIntonation == "Rising-Falling"){
          if((getLastTime() - beepPhase) < (beepCycle / beepTempo + ((n + 1)) * soundDuration)){

            buzzer.tone(currentPitch, soundDuration * 1000);
            _delay(float(silenceDuration));

          }else{
            n += 1;
            if(n < 12){
              currentPitch = exp((log(beepPitch) + (n / 12) * log(2)));

            }else{
              currentPitch = exp((log(beepPitch) + (((24 - n)) / 12) * log(2)));

            }

          }

        }
        if(beepIntonation == "Falling-Rising"){
          if((getLastTime() - beepPhase) < (beepCycle / beepTempo + ((n + 1)) * soundDuration)){

            buzzer.tone(currentPitch, soundDuration * 1000);
            _delay(float(silenceDuration));

          }else{
            n += 1;
            if(n < 12){
              currentPitch = exp((log(beepPitch) - (n / 12) * log(2)));

            }else{
              currentPitch = exp((log(beepPitch) - (((24 - n)) / 12) * log(2)));

            }

          }

        }

      }
      if((getLastTime() - beepPhase) > ((beepCycle + 1)) / beepTempo){
        beepCycle += 1;
        n = 0;

      }

    }

  }

  rgbled_7.setColor(0, 0, 0, 0);
  rgbled_7.show();
  motor_9.run(0);
  motor_10.run(0);

}
void CheckValidWanderInput_N_S_N_N_N(double speed, String acceleration, double roundness, double turnRate, double phase){
  if((turnRate > 0)  &&  ((((phase > 0)  ||  (phase == 0.000000)))  &&  ((((acceleration == "Constant")  ||  ((acceleration == "Rising")  ||  (acceleration == "Falling"))))  &&  (((((speed < 100)  ||  (speed == 100.000000)))  &&  (speed > 0))  &&  ((((roundness > 0)  ||  (roundness == 0.000000)))  &&  (((roundness < 1)  ||  (roundness == 1.000000)))))))){
    doWander = 1;

  }else{
    doWander = 0;

  }

}
void CheckValidBlinkInput_N_N_S_N(double temperature, double tempo, String mode, double phase){
  if((tempo > 0)  &&  ((((phase > 0)  ||  (phase == 0.000000)))  &&  (((((temperature > 0)  ||  (temperature == 0.000000)))  &&  (((temperature < 1)  ||  (temperature == 1.000000))))  &&  (((mode == "Constant")  ||  ((mode == "Rising")  ||  ((mode == "Falling")  ||  ((mode == "Rising-Falling")  ||  (mode == "Falling-Rising"))))))))){
    doBlink = 1;

  }else{
    doBlink = 0;

  }

}
void CheckValidBeepInput_N_N_S_N(double pitch, double tempo, String intonation, double phase){
  if((tempo > 0)  &&  ((((phase > 0)  ||  (phase == 0.000000)))  &&  (((pitch > 0)  &&  (pitch < 5000))  &&  (((intonation == "Constant")  ||  ((intonation == "Rising")  ||  ((intonation == "Falling")  ||  ((intonation == "Rising-Falling")  ||  (intonation == "Falling-Rising"))))))))){
    doBeep = 1;

  }else{
    doBeep = 0;

  }

}

void _delay(float seconds) {
  long endTime = millis() + seconds * 1000;
  while(millis() < endTime) _loop();
}

void setup() {
  pinMode(A7, INPUT);
  rgbled_7.fillPixelsBak(0, 2, 1);
  timesButtonPressed = 0;
  while(1) {
      if((0 ^ (analogRead(A7) > 10 ? 0 : 1))){
        timesButtonPressed += 1;
        if(timesButtonPressed == 1.000000){
          WanderBlinkBeep_N_wander_N_S_N_N_N_B_blink_N_N_S_N_beep_N_N_S_N(5, 100, "Constant", 1, 0.6, 0, 0.000000 == 1.000000, 0, 0, "", 0, 0, 0, "", 0);

        }
        if(timesButtonPressed == 2.000000){
          WanderBlinkBeep_N_wander_N_S_N_N_N_B_blink_N_N_S_N_beep_N_N_S_N(5, 100, "Constant", 0, 1, 0, 0.000000 == 1.000000, 0, 0, "0", 0, 0, 0, "", 0);

        }
        if(timesButtonPressed == 3.000000){
          WanderBlinkBeep_N_wander_N_S_N_N_N_B_blink_N_N_S_N_beep_N_N_S_N(5, 100, "Constant", 1, 0.6, 0, 0.000000 == 1.000000, 0.9, 1, "Rising-Falling", 0, 0, 0, "", 0);

        }
        if(timesButtonPressed == 4.000000){
          WanderBlinkBeep_N_wander_N_S_N_N_N_B_blink_N_N_S_N_beep_N_N_S_N(5, 100, "Constant", 1, 0.6, 0, 0.000000 == 1.000000, 0.1, 1, "Rising-Falling", 0, 0, 0, "", 0);

        }
        if(timesButtonPressed == 5.000000){
          WanderBlinkBeep_N_wander_N_S_N_N_N_B_blink_N_N_S_N_beep_N_N_S_N(5, 100, "Constant", 1, 0.6, 0, 0.000000 == 1.000000, 0.1, 1, "Rising-Falling", 0, 440, 1, "Rising", 0);

        }

      }

      _loop();
  }

}

void _loop() {
}

void loop() {
  _loop();
}